### ISSUE TITLE
remarkBreaks

### ISSUE THREAD

**Issue by calumk** [chrisweb/rehype-github-alerts#4] opened 2024-01-17 13:24 UTC
Thanks for this repo!

It Might be worth updating the readme to specify /why/ you need remarkBreaks.... because otherwise it wont work unless you put two spaces.

I Spent some time (10 mins) trying to debug this, downloading and testing the example repo, assuming the parser wasnt working properly before I went back and understood exactly why your test code has 2 spaces in it.

**Comment by chrisweb** [comment] 2024-01-19 12:18
Thank you for your feedback :)

hmmmm I have this section in the readme: <https://github.com/chrisweb/rehype-github-alerts?tab=readme-ov-file#about-soft-line-breaks-support>

I'm not sure how I can make it better, did you see that section and it still wasn't clear? 

If it is a visibility thing I could move it up, or maybe link to that section from within a section that is more at top, like adding a tip just below the installation guide

It is more a wording thing, so clarify the matter better, then maybe I can try to think of a more "explicit" way, but I'm not really sure how, do you have a suggestion how I could explain this better?

Regarding line breaks, just a side note about something I noticed a few days ago: I'm currently using the github alerts extensivly in a project and I came accross a problem where I wanted to add multiple paragraphs of text to an alert, but the result was not what I expected, (I have a bit of trouble finding the right words to explain this right now) the text was too "compact", I expected it have "more breathing space", so I actually installed remark breaks but it did not make any difference, with or without it the text was just one big chunk, if I write text outside of a blockquote, every double space at the end of a line of text will result in the next line to be in a seperate paragraph element when transformed to html, this is not the case inside of blockquotes, I have added this to my todo list as I need to investigate the causes and also verify what the results are on github and then I need to think of how to solve it, what I did for now is to create my alert like this:

```md
> [!TIP]
> very long sentence / paragraph one
>
> very long sentence / paragraph two
```

> [!TIP]
> very long sentence / paragraph one
> very long sentence / paragraph two

**Comment by ShivamJoker** [comment] 2024-03-01 19:32
I also faced the same issue.
Had to install line break plugin and it added BR everywhere then again had to change the styling to make br display none;

**Comment by chrisweb** [comment] 2024-03-02 18:38
Yeah the line break plugin in great in some situations to turn soft breaks into hard breaks, but it does not help for text inside of  blockquotes / alerts

The only solution with this plugin is to add a "blank line" like so:

```
> [!TIP]
> very long sentence / paragraph one
>
> very long sentence / paragraph two
```

which then renders like this:

> [!TIP]
> very long sentence / paragraph one
>
> very long sentence / paragraph two

this is how github does it and the result when using the plugin is the same

**Comment by ShivamJoker** [comment] 2024-03-02 20:01
@chrisweb in my case the below example didn't work without the line break plugin

> [!TIP]
> very long sentence / paragraph one
> very long sentence / paragraph two

**Comment by chrisweb** [comment] 2024-03-03 22:42
Yes I understand what you mean... It only works without the [remark-breaks](https://github.com/remarkjs/remark-breaks) if you add **2 spaces** after each line, including the first line` > [!TIP]  `

Hmmm, I will try to improve the Readme of this plugin tomorrow to make it more clear that 2 spaces are required or that the alternative is to install remark-breaks

**Comment by chrisweb** [comment] 2024-03-04 21:32
@calumk @ShivamJoker I have published a new beta https://www.npmjs.com/package/rehype-github-alerts/v/3.0.0-beta.1 that should improve the DX of this package, it can be installed using the beta tag:

```shell
npm i rehype-github-alerts@beta
```

This new version will read the alert title and ignore if it ends with a hard line break or not, meaning you don't need to add double spaces after the **[!NOTE]** alert type anymore for it to work (and also don't need the optional remark-breaks package)

I released a beta for now, so that the new behavior can be tested and to verify that this does not introduce new bug(s), I will wait a few days and if after that there are no bug reports I will publish the new version

please let me know if this version works better for you 🤞

**Comment by calumk** [comment] 2024-03-04 22:17
I am no longer actively using this plugin, as I switched away from remark for unrelated reasons, but it seems like a good idea to update as you have 

Thanks for continuing to work on this

**Comment by ShivamJoker** [comment] 2024-03-05 06:12
@chrisweb If I add two spaces after `![NOTE]` it works but without it, it only shows only one paragraph with newline above paragraph.

```
> [!WARNING]
> For now, LLRT is an **experimental** package.
> It is subject to change and intended only for testing purposes.
```

![image](https://github.com/chrisweb/rehype-github-alerts/assets/23727670/16033f01-162d-4827-bec7-be55da61cbe5)

**Comment by chrisweb** [comment] 2024-03-05 20:08
@ShivamJoker thank you for testing the beta.1, there was indeed a bug when the line after the type does not only contain text, I fixed it and released a new beta.2 <https://www.npmjs.com/package/rehype-github-alerts/v/3.0.0-beta.2>

**Comment by ShivamJoker** [comment] 2024-03-06 09:55
HI @chrisweb it works now.
Thanks a ton.

There is can be one more improve of not adding newline in the beginning of the paragraph.

```
<div class="markdown-alert markdown-alert-tip">
<p class="markdown-alert-title"><svg/>Tip</p><p> <-- This paragraph should be with text below
If you want to change your Lambda file and function name you can update it in the handler.</p>
</div>
```

**Comment by chrisweb** [comment] 2024-03-06 17:33
@ShivamJoker I'm glad it works now 🙂 and thank you again for taking the time to test it

Ah yes I see what you mean, good catch, indeed I could probably fix the placement of the first paragraph element, I will look into this

**Comment by chrisweb** [comment] 2024-03-10 21:38
v3 is out https://www.npmjs.com/package/rehype-github-alerts/v/3.0.0

I'm closing this, but if you still have problems or similar problems, then please open a new ticket

**Closed by chrisweb** 2024-03-10 21:38 UTC
Labels: documentation, feedback

**Comment by ShivamJoker** [comment] 2024-03-11 04:43
Thanks @chrisweb
